package models

type AutoGenerated struct {
	RestJobDefinitionModel RestJobDefinitionModel `json:"restJobDefinitionModel"`
	RestJobObjectsModels   []RestJobObjectsModels `json:"restJobObjectsModels"`
	RestJobSettingsModel   RestJobSettingsModel   `json:"restJobSettingsModel"`
}
type RestJobDefinitionModel struct {
	AllBackupObjects       bool   `json:"allBackupObjects,omitempty"`
	AutoRetire             bool   `json:"autoRetire,omitempty"`
	BackupName             string `json:"backupName,omitempty"`
	BackupVersion          *int   `json:"backupVersion,omitempty"`
	DataDictionaryType     string `json:"dataDictionaryType"`
	JobDescription         string `json:"jobDescription"`
	JobName                string `json:"jobName"`
	JobType                string `json:"jobType"`
	NextIncrementalRestore bool   `json:"nextIncrementalRestore"`
	RetireUnits            string `json:"retireUnits"`
	RetireValue            int    `json:"retireValue"`
	SavesetAccountID       string `json:"savesetAccountId"`
	SavesetPassword        string `json:"savesetPassword"`
	SavesetUser            string `json:"savesetUser"`
	SourceSystem           string `json:"sourceSystem"`
	SrcUserAccountID       string `json:"srcUserAccountId"`
	SrcUserName            string `json:"srcUserName"`
	SrcUserPassword        string `json:"srcUserPassword"`
	TargetGroupName        string `json:"targetGroupName"`
	TargetSystem           string `json:"targetSystem"`
	TargetUserAccountID    string `json:"targetUserAccountId"`
	TargetUserName         string `json:"targetUserName"`
	TargetUserPassword     string `json:"targetUserPassword"`
}

type RestJobObjectsModels struct {
	ConfigMapName  string           `json:"configMapName"`
	ExcludeObjects []ExcludeObjects `json:"excludeObjects"`
	IncludeAll     bool             `json:"includeAll"`
	MapTo          string           `json:"mapTo"`
	ObjectName     string           `json:"objectName"`
	ObjectType     string           `json:"objectType"`
	ParentName     string           `json:"parentName"`
	ParentType     string           `json:"parentType"`
	RenameTo       string           `json:"renameTo"`
}
type RestJobSettingsModel struct {
	BlockLevelCompression     string `json:"blockLevelCompression"`
	ConfigMapName             string `json:"configMapName"`
	DisableFallback           bool   `json:"disableFallback"`
	DsmainJSONLogging         bool   `json:"dsmainJsonLogging"`
	EnableBackupForIr         bool   `json:"enableBackupForIr"`
	EnableIncrementalRestore  bool   `json:"enableIncrementalRestore"`
	EnableTemperatureOverride bool   `json:"enableTemperatureOverride"`
	LoggingLevel              string `json:"loggingLevel"`
	MapTo                     string `json:"mapTo"`
	Nosync                    bool   `json:"nosync"`
	Nowait                    bool   `json:"nowait"`
	NumberParallelBuilds      int    `json:"numberParallelBuilds"`
	Online                    bool   `json:"online"`
}
